name: Deploy (staging)

on:
  workflow_run:
    workflows: ['Validate'] # must match validate.yml's name
    types: [completed]
    branches: [main]

concurrency:
  group: cf-worker-staging
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      deployments: write
    steps:
      - name: ‚¨áÔ∏è Checkout the validated commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: üì• Install deps
        run: pnpm i --frozen-lockfile

      - name: üèóÔ∏è Build (inject staging vars)
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          ENV_NAME: staging
          PUBLIC_UMAMI_SITE_ID: ${{ vars.PUBLIC_UMAMI_SITE_ID }}
          PUBLIC_UMAMI_SHARE_URL: ${{ vars.PUBLIC_UMAMI_SHARE_URL}}
        run: pnpm build

      - name: üöÄ Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env staging
